default: 
    autoload:
        '': '%paths.base%/../features/bootstrap'
    suites:
        default:
            paths: ['../features/single']
            contexts:
                - FeatureContext:
                    parameters:
                        server: "hub-cloud.browserstack.com"
                        user: "BROWSERSTACK_USERNAME"
                        key: "BROWSERSTACK_ACCESS_KEY"

                        capabilities:
                            build: "browserstack build 1"
                            name: "BStack parallel test"
                            "browserstack.debug": true
                            "browserstack.source": "behat:sample-master-v1.0"

                        environments:
                            -
                                browser: "Chrome"
                                browser_version: "latest"
                            -
                                browser: "Firefox"
                                os: "Windows"
                            -
                                browser: "Safari"
                                os: "OS X"
                            -
                                browser: "Internet explorer"
                                os: "Windows"
